#  Github: https://github.com/H3rzius/CustomCommands
#
#                                CONFIG FILE
#                                 @H3rzius
#
#
#                                    ██
#                                  ██░░██
#                                ██░░░░░░██
#                              ██░░░░░░░░░░██
#                              ██░░░░░░░░░░██
#                            ██░░░░░░░░░░░░░░██
#                          ██░░░░░░██████░░░░░░██
#                          ██░░░░░░██████░░░░░░██
#                        ██░░░░░░░░██████░░░░░░░░██
#                        ██░░░░░░░░██████░░░░░░░░██
#                      ██░░░░░░░░░░██████░░░░░░░░░░██
#                    ██░░░░░░░░░░░░██████░░░░░░░░░░░░██
#                    ██░░░░░░░░░░░░██████░░░░░░░░░░░░██
#                  ██░░░░░░░░░░░░░░██████░░░░░░░░░░░░░░██
#                  ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██
#                ██░░░░░░░░░░░░░░░░██████░░░░░░░░░░░░░░░░██
#                ██░░░░░░░░░░░░░░░░██████░░░░░░░░░░░░░░░░██
#              ██░░░░░░░░░░░░░░░░░░██████░░░░░░░░░░░░░░░░░░██
#              ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██
#                ██████████████████████████████████████████
#
#                                 WARNING:
#
#     Removing variables from file can fail the message output for command.
#             If something happen, you can reinstall the plugin
#                     deleting the plugin folder and
#                the next server restart installs himself.
#
#
# main part
no-permissions: 'No tienes permisos para ejecutar este comando'
as-console: 'Solo jugadores pueden ejecutar el comando'
disable-plugin: 'Plugin deshabilitado, puede que sea un problema al cargar el plugin'

#enable commands
enable-troll-cmd: true
enable-adios-cmd: true
enable-pvp-cmd: true
enable-hack-cmd: false

# h3r command part
h3r-help: 'Plugin creado por H3rzius :>'

# adios command part
adios-top: '<player> descubrio el secreto del suicide top'
adios-message: 'F'

# pvp command part
activate-pvp: 'PvP Activado'
deactivate-pvp: 'PvP Desactivado'

# troll command part
trolled: 'Fuiste troleado xd'
trolled-yourself: 'Te troleaste a ti mismo xd'
got-trolled: 'Has troleado a <player>'

# staff command part
stafftools: 'PROXIMAMENTE...'

# hack command part
hack-cmd-help: 'Usa /hack <jugador>'
time-ban: '60d'
time-banip: '7d'
reason-ban: 'Uso de hacks o cliente modificado no permitido en el servidor'
reason-banip: 'Uso de hacks... Tienes 7 días para apelar, caso contrario continua los 60 días de sanción'
