#  Github: https://github.com/H3rzius/CustomCommands
#
#                                CONFIG FILE
#                                 @H3rzius
#
#
#                                    ██
#                                  ██░░██
#                                ██░░░░░░██
#                              ██░░░░░░░░░░██
#                              ██░░░░░░░░░░██
#                            ██░░░░░░░░░░░░░░██
#                          ██░░░░░░██████░░░░░░██
#                          ██░░░░░░██████░░░░░░██
#                        ██░░░░░░░░██████░░░░░░░░██
#                        ██░░░░░░░░██████░░░░░░░░██
#                      ██░░░░░░░░░░██████░░░░░░░░░░██
#                    ██░░░░░░░░░░░░██████░░░░░░░░░░░░██
#                    ██░░░░░░░░░░░░██████░░░░░░░░░░░░██
#                  ██░░░░░░░░░░░░░░██████░░░░░░░░░░░░░░██
#                  ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██
#                ██░░░░░░░░░░░░░░░░██████░░░░░░░░░░░░░░░░██
#                ██░░░░░░░░░░░░░░░░██████░░░░░░░░░░░░░░░░██
#              ██░░░░░░░░░░░░░░░░░░██████░░░░░░░░░░░░░░░░░░██
#              ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██
#                ██████████████████████████████████████████
#
#                                 WARNING:
#
#     Removing variables from file can fail the message output for command.
#             If something happen, you can reinstall the plugin
#                     deleting the plugin folder and
#                the next server restart installs himself.
#
#
# main part
no-permissions: 'No tienes permisos para ejecutar este comando'
player-not-entered: 'nunca ha entrado al servidor!'
as-console: 'Solo jugadores pueden ejecutar el comando'
disable-plugin: 'Plugin deshabilitado, puede que sea un problema al cargar el plugin'
reload: 'El plugin ha sido recargado'
reload-failed: 'El plugin no pudo recargar, no existe ese plugin'

#enable commands
enable-troll-cmd: true
enable-adios-cmd: true
enable-pvp-cmd: true
enable-hack-cmd: true

# h3r command part
h3r-help: 'Plugin creado por H3rzius :>'
h3r-status: 'Jugador: %player_name%'
h3r-easteregg: 'H3rzius pasó por aquí'

# adios command part
adios-top: '<player> descubrio el secreto del suicide top'
adios-message: 'F'

# pvp command part
activate-pvp: 'PvP Activado'
deactivate-pvp: 'PvP Desactivado'

# troll command part
trolled: 'Fuiste troleado xd'
trolled-yourself: 'Te troleaste a ti mismo xd'
got-trolled: 'Has troleado a <player>'

# staff command part
stafftools-activate: 'Modo Staff se ha activado'
stafftools-deactivate: 'Modo Staff se ha desactivado'
cant-save-data: 'El archivo staffdata.yml no pudo guardarse:'

# hack command part
hack-cmd-help: 'Usa /hack <jugador>'
time-ban: '60d'
time-banip: '7d'
reason-ban: 'Uso de hacks o cliente modificado no permitido en el servidor'
reason-banip: 'Tienes 7 días para apelar. Baneo original: 60 Días'

# survey command part
survey: '[SURVEY]'
survey-cmd-1: 'yes'
survey-cmd-2: 'no'
survey-player: 'players'
survey-answer: 'Answer with /yes or /no'
survey-yes: 'says yes'
survey-no: 'says no'
no-surveys: 'There is no survey in progress.'
