name: H3rCustomCommands
version: '${project.version}'
main: me.h3rzius.h3rcustomcommands.H3rCustomCommands
authors: [ H3rzius ]
description: Comandos unicos creados por H3rzius
commands:
  h3r:
    description: Info basica del plugin
    usage: /h3r
    aliases: h3rzius
  adios:
    description: Te quita la vida f
    usage: /adios
    aliases: ay
  pvp:
    description: (Des)Activa el PvP
    usage: /pvp
    aliases: [tpvp, apvp]
    permission: h3rcustomcommands.pvp
  troll:
    description: Troleas a un usuario con ruidos y efectos molestos
    usage: /troll
    aliases: [jaja, xd]
    permission: h3rcustomcommands.troll
  stafftools:
    description: Abres el panel de staffs
    usage: /stafftools
    aliases: [stafft, staff]
    permission: h3rcustomcommands.stafftools
