name: H3rCustomCommands
version: '${project.version}'
main: me.h3rzius.h3rcustomcommands.H3rCustomCommands
authors: [ H3rzius ]
description: Comandos unicos creados por H3rzius
commands:
  h3r:
    description: Info basica del plugin
    usage: /h3r [reload/help/check]
    default: true
    aliases: h3rzius

  suicidetop:
    description: suicide top?
    usage: /suicidetop

  turnswitch:
    description: enables or disables an command from CustomCommands
    usage: /turnswitch
    aliases: [activar, desactivar]
    permission: h3rcustomcommands.switch

  pvp:
    description: (Des)Activa el PvP
    usage: /pvp
    aliases: [tpvp, apvp]
    permission: h3rcustomcommands.pvp

  troll:
    description: Troleas a un usuario con ruidos y efectos molestos
    usage: /troll
    aliases: [jaja, xd]
    permission: h3rcustomcommands.troll

  stafftools:
    description: Abres el panel de staffs
    usage: /stafftools [warp]
    aliases: [stafft, staff]
    permission: h3rcustomcommands.stafftools

  hack:
    description: Sends a custome ban for hackers
    usage: /hack [-r <reason>] <player>
    permission: h3rcustomcommands.hack

  survey:
    description: Creates a survey and users can participate
    usage: /survey [yes/no] <title> <question>
    aliases:
      - encuesta
      - pregunta

